CREATE TABLE social_links(
    id BIGSERIAL PRIMARY KEY,
    platform VARCHAR(50) NOT NULL,
    link_url TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);