CREATE TABLE site_settings(
    id BIGSERIAL PRIMARY KEY,
    settings_key VARCHAR(100) NOT NULL UNIQUE,
    settings_value TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);